SIG-1647 Fix existing PHP verifications and add new verifications
Evidos/signhost-phpdemoclient pull request #8
Opened 2017-06-26 12:05 UTC by ATimmeh33

2017-06-26 12:11 UTC, MrJoe commented on signhost.php
> +    public $Bsn; // String
Wrong indent

2017-06-26 12:12 UTC, MrJoe requested changes

2017-06-26 12:12 UTC, MrJoe commented on signhost.php
> +    public $RequireHandsignature; // Bool
Wrong indent

2017-06-26 12:12 UTC, MrJoe commented on signhost.php
> +    public $Number; // String
Wrong indent

2017-06-27 12:35 UTC, MrJoe requested changes

2017-06-27 12:35 UTC, MrJoe commented on signhost.php
>      public $Iban; // String
Maybe document the properties with @var syntax?
https://stackoverflow.com/questions/2194822/how-to-document-class-properties-in-php-5-with-phpdocumentor#2194835
Don't if there are also tags for readonly and optional

2017-08-14 08:23 UTC, MrJoe commented on signhost.php
> +	public $RequireScribble;
Should be part of verifications array

2017-08-14 08:25 UTC, MrJoe requested changes
Old verification properties should be removed

2017-08-14 08:25 UTC, MrJoe commented on signhost.php
> +	public $RequireScribble;
Should be part of verifications array

2017-08-14 08:25 UTC, MrJoe commented on signhost.php
> +	public $RequireSmsVerification;
Should be part of verifications array

2017-08-14 08:25 UTC, MrJoe commented on signhost.php
> +	public $RequireDigidVerification;
Should be part of verifications array

2017-08-14 08:25 UTC, MrJoe commented on signhost.php
> +	public $RequireKennisnetVerification;
Should be part of verifications array

2017-08-14 08:25 UTC, MrJoe commented on signhost.php
> +	public $RequireSurfnetVerification;
Should be part of verifications array

2017-08-14 08:25 UTC, MrJoe commented on signhost.php
> +	public $ScribbleName;
Should be part of verifications array

2017-08-14 08:25 UTC, MrJoe commented on signhost.php
> +	public $ScribbleNameFixed;
Should be part of verifications array

2019-11-04 14:07 UTC, ATimmeh33 commented
4350286c02712be9f3010cf2eefdd759cd3f4b2c is no longer needed, already done in https://github.com/Evidos/signhost-phpdemoclient/pull/18

2019-11-25 13:46 UTC, ATimmeh33 commented
Obsoleted by https://github.com/Evidos/signhost-phpdemoclient/pull/21

2019-11-25 13:46 UTC, closed without merging